{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: sqlalchemy in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (2.0.9)\n",
      "Requirement already satisfied: typing-extensions>=4.2.0 in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from sqlalchemy) (4.4.0)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from sqlalchemy) (2.0.1)\n",
      "Requirement already satisfied: ipython-sql in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (0.5.0)\n",
      "Requirement already satisfied: sqlparse in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from ipython-sql) (0.4.4)\n",
      "Requirement already satisfied: six in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from ipython-sql) (1.16.0)\n",
      "Requirement already satisfied: prettytable in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from ipython-sql) (3.7.0)\n",
      "Requirement already satisfied: sqlalchemy>=2.0 in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from ipython-sql) (2.0.9)\n",
      "Requirement already satisfied: ipython in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from ipython-sql) (8.10.0)\n",
      "Requirement already satisfied: ipython-genutils in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from ipython-sql) (0.2.0)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from sqlalchemy>=2.0->ipython-sql) (2.0.1)\n",
      "Requirement already satisfied: typing-extensions>=4.2.0 in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from sqlalchemy>=2.0->ipython-sql) (4.4.0)\n",
      "Requirement already satisfied: pickleshare in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from ipython->ipython-sql) (0.7.5)\n",
      "Requirement already satisfied: backcall in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from ipython->ipython-sql) (0.2.0)\n",
      "Requirement already satisfied: decorator in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from ipython->ipython-sql) (5.1.1)\n",
      "Requirement already satisfied: jedi>=0.16 in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from ipython->ipython-sql) (0.18.1)\n",
      "Requirement already satisfied: appnope in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from ipython->ipython-sql) (0.1.2)\n",
      "Requirement already satisfied: matplotlib-inline in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from ipython->ipython-sql) (0.1.6)\n",
      "Requirement already satisfied: stack-data in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from ipython->ipython-sql) (0.2.0)\n",
      "Requirement already satisfied: pygments>=2.4.0 in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from ipython->ipython-sql) (2.11.2)\n",
      "Requirement already satisfied: traitlets>=5 in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from ipython->ipython-sql) (5.7.1)\n",
      "Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.30 in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from ipython->ipython-sql) (3.0.36)\n",
      "Requirement already satisfied: pexpect>4.3 in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from ipython->ipython-sql) (4.8.0)\n",
      "Requirement already satisfied: wcwidth in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from prettytable->ipython-sql) (0.2.5)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.0 in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)\n",
      "Requirement already satisfied: ptyprocess>=0.5 in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)\n",
      "Requirement already satisfied: pure-eval in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from stack-data->ipython->ipython-sql) (0.2.2)\n",
      "Requirement already satisfied: executing in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from stack-data->ipython->ipython-sql) (0.8.3)\n",
      "Requirement already satisfied: asttokens in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (from stack-data->ipython->ipython-sql) (2.0.5)\n"
     ]
    }
   ],
   "source": [
    "!pip install sqlalchemy\n",
    "!pip install ipython-sql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: psycopg2-binary in /Users/da_m1_36/anaconda3/lib/python3.10/site-packages (2.9.6)\n"
     ]
    }
   ],
   "source": [
    "!pip install psycopg2-binary"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext sql\n",
    "from sqlalchemy import create_engine\n",
    "%sql postgresql://postgres:polpol@localhost:5434/food_ordering_system"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "def search():\n",
    "    search = input(\"Please insert order num you want to search for:\")\n",
    "    %sql  select * from orders where order_number = {search}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def search_sales_list():\n",
    "    search_sales_list = input(\"Please insert food name you want to search for:\")\n",
    "    %sql SELECT sum(total_cost) as \"Total Cost\", sum(item_num) as \"Number of '{search_sales_list}'\" from orders where food_name =  '{search_sales_list}';"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def cancel_order():\n",
    "    order_number = input(\"Please insert order number you want to cancel: \")\n",
    "    %sql UPDATE orders SET ORDER_STATUS = 'cancelled' where order_number = order_number"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "def payment(order_num):    \n",
    "\n",
    "    var1 = %sql SELECT total_cost, payment_status FROM orders where orders.order_id = {order_num};\n",
    "    var2= %sql Select cash, card FROM store_acc;\n",
    "\n",
    "    payment_status = var1[0][1]\n",
    "    cash = var2[0][0]\n",
    "    card = var2[0][1]\n",
    "    total_cost = float(var1[0][0])\n",
    "\n",
    "    if payment_status == \"Not Paid\":\n",
    "        \n",
    "            pt = int(input(\"enter payment type: 1 for cash and 2 for card\"))\n",
    "            if pt == 1: \n",
    "                var7 = %sql UPDATE orders SET payment_status = 'Paid' where order_id = {order_num}\n",
    "                var6 = %sql UPDATE store_acc SET cash = {cash} + {total_cost}\n",
    "            elif pt == 2:\n",
    "                account_num = input(\"Enter Acc Number\")\n",
    "                pin_num = input(\"Enter pin Number\")\n",
    "                var3= %sql Select balance FROM bank where bank.account_num = {account_num} and bank.pin_num ={pin_num}\n",
    "                bank_bal = float(var3[0][0])\n",
    "\n",
    "                if total_cost < bank_bal:\n",
    "                    var5 = %sql UPDATE bank SET balance = {bank_bal} - {total_cost} where bank.account_num = {account_num} and bank.pin_num ={pin_num}\n",
    "                    var7 = %sql UPDATE orders SET payment_status = 'Paid' where order_id = {order_num}\n",
    "                    var6 = %sql UPDATE store_acc SET card = {card} + {total_cost}\n",
    "                else:\n",
    "                    print(\"Insufficient funds in account\")\n",
    "            else:\n",
    "                print(\"invalid option\")\n",
    "            \n",
    "        \n",
    "    else:\n",
    "        print(\"Order already paid\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "def edit_order2():   \n",
    "    menu = {\n",
    "        'burger': 40.00,\n",
    "        'drink': 15.00,\n",
    "        'fries': 20.00,\n",
    "        'wraps': 32.00,\n",
    "        'wings': 43.00,\n",
    "        'lamb chops': 76.00,\n",
    "    }\n",
    "    \n",
    "    answer = input(\"Would you like to edit your order? (Y/N): \")\n",
    "    if answer.upper() == \"Y\":\n",
    "        onum = int(input(\"Please enter your order number: \"))\n",
    "        edit_answer = input(\"Would you like to Add or Remove an item? (Add/Remove): \")\n",
    "        if edit_answer.lower() == \"remove\":\n",
    "            edit_item = input(\"Please enter the item that you want to remove in order: \")\n",
    "            num_of_items = int(input(\"Please insert the number of items you want to remove again: \"))\n",
    "            \n",
    "            var2 = %sql SELECT item_no, total_cost FROM orders WHERE order_number = {onum} AND food_name = '{edit_item}';\n",
    "            itemno = int(var2[0][0])\n",
    "            counter = 0\n",
    "            while num_of_items > itemno and counter < 3:\n",
    "                print(\"Invalid input. You cannot remove more items than are in your order.\")\n",
    "                num_of_items = int(input(\"Please insert the number of items you want to remove again: \"))\n",
    "                counter += 1\n",
    "            \n",
    "            if num_of_items > itemno:\n",
    "                print(\"Maximum number of attempts exceeded. Exiting...\")\n",
    "                exit  \n",
    "                \n",
    "            else:\n",
    "                total = menu[edit_item] * num_of_items\n",
    "                total_cost -= total\n",
    "                %sql UPDATE orders SET item_no = item_no - {num_of_items}, total_cost = total_cost - {total} WHERE order_number = {onum} AND food_name = '{edit_item}'\n",
    "        else:\n",
    "            print(\"The selected food item is not in your order.\")\n",
    "    else:\n",
    "        print(\"The selected food item\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "def edit_order1():\n",
    "    # Define the menu\n",
    "    menu = {\n",
    "        'burger': 40.00,\n",
    "        'drink': 15.00,\n",
    "        'fries': 20.00,\n",
    "        'wraps': 32.00,\n",
    "        'wings': 43.00,\n",
    "        'lamb chops': 76.00,\n",
    "    }\n",
    "\n",
    "    # Prompt the user to enter their order number\n",
    "    total_cost = 0\n",
    "   \n",
    "    answer = input(\"Would you like to edit your order? (Y/N): \")\n",
    "    if answer.upper() == \"Y\":\n",
    "        onum = int(input(\"Please enter your order number: \"))\n",
    "        edit_answer = input(\"Would you like to Add or Remove an item? (Add/Remove): \")\n",
    "        if edit_answer.lower() == \"add\":\n",
    "            edit_item = input(\"Is the item that you want to add in order? Y/N\")\n",
    "            if edit_item.lower() == 'y':\n",
    "                edit_item = input(\"Please enter item you would like to edit: \")\n",
    "                num_of_items = int(input(\"Please insert the total number of items you want to add:\"))\n",
    "               \n",
    "                if edit_item in menu:\n",
    "                    var1 = %sql SELECT item_no, total_cost FROM orders WHERE order_number = {onum} AND food_name = '{edit_item}';\n",
    "                    itemno = int(var1[0][0])\n",
    "                    totalcost = float(var1[0][1])\n",
    "                    total = menu[edit_item] * num_of_items\n",
    "                    total_cost += total\n",
    "                    %sql UPDATE orders SET item_no ={itemno} + {num_of_items}, total_cost=  {totalcost} + {total_cost} WHERE order_number = {onum} AND food_name = '{edit_item}';\n",
    "\n",
    "            if edit_item.lower() =='n':\n",
    "                take_order(onum)\n",
    "        \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The sql extension is already loaded. To reload it, use:\n",
      "  %reload_ext sql\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 3275, in raw_connection\n",
      "    return self.pool.connect()\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 455, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 1271, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 719, in checkout\n",
      "    rec = pool._do_get()\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/pool/impl.py\", line 168, in _do_get\n",
      "    with util.safe_reraise():\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 147, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/pool/impl.py\", line 166, in _do_get\n",
      "    return self._create_connection()\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 396, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 681, in __init__\n",
      "    self.__connect()\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 905, in __connect\n",
      "    with util.safe_reraise():\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 147, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/create.py\", line 636, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/default.py\", line 580, in connect\n",
      "    return self.loaded_dbapi.connect(*cargs, **cparams)\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/psycopg2/__init__.py\", line 122, in connect\n",
      "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
      "psycopg2.OperationalError: connection to server at \"localhost\" (::1), port 5430 failed: Connection refused\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "connection to server at \"localhost\" (127.0.0.1), port 5430 failed: Connection refused\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sql/magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sql/connection.py\", line 70, in set\n",
      "    cls.current = existing or Connection(descriptor, connect_args, creator)\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sql/connection.py\", line 55, in __init__\n",
      "    self.internal_connection = engine.connect()\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 3251, in connect\n",
      "    return self._connection_cls(self)\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 147, in __init__\n",
      "    Connection._handle_dbapi_exception_noconnection(\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 2413, in _handle_dbapi_exception_noconnection\n",
      "    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 3275, in raw_connection\n",
      "    return self.pool.connect()\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 455, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 1271, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 719, in checkout\n",
      "    rec = pool._do_get()\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/pool/impl.py\", line 168, in _do_get\n",
      "    with util.safe_reraise():\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 147, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/pool/impl.py\", line 166, in _do_get\n",
      "    return self._create_connection()\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 396, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 681, in __init__\n",
      "    self.__connect()\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 905, in __connect\n",
      "    with util.safe_reraise():\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 147, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/create.py\", line 636, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/default.py\", line 580, in connect\n",
      "    return self.loaded_dbapi.connect(*cargs, **cparams)\n",
      "  File \"/Users/da_m1_36/anaconda3/lib/python3.10/site-packages/psycopg2/__init__.py\", line 122, in connect\n",
      "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
      "sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at \"localhost\" (::1), port 5430 failed: Connection refused\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "connection to server at \"localhost\" (127.0.0.1), port 5430 failed: Connection refused\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys(['postgresql://postgres:***@localhost:5434/food_ordering_system'])\n",
      "\n",
      "choose an option\n",
      "1-Order_food\n",
      "2-Edit_order\n",
      "3-Cancel_order\n",
      "4-Search_order\n",
      "5-search_sales_list\n",
      "\n",
      "Your order number:  206\n",
      " * postgresql://postgres:***@localhost:5434/food_ordering_system\n",
      "(psycopg2.errors.UndefinedColumn) column \"item_no\" of relation \"orders\" does not exist\n",
      "LINE 1: ...ert into orders(order_number,dates,hour,food_name,item_no,or...\n",
      "                                                             ^\n",
      "\n",
      "[SQL: insert into orders(order_number,dates,hour,food_name,item_no,order_status,payment_status,total_cost)values(206,'2023-05-05','14:32:20','burger',5,'Preparing','Not Paid',200.0);]\n",
      "(Background on this error at: https://sqlalche.me/e/20/f405)\n",
      "Total cost: 200.00\n",
      " * postgresql://postgres:***@localhost:5434/food_ordering_system\n",
      "0 rows affected.\n",
      " * postgresql://postgres:***@localhost:5434/food_ordering_system\n",
      "1 rows affected.\n"
     ]
    },
    {
     "ename": "IndexError",
     "evalue": "list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[23], line 85\u001b[0m\n\u001b[1;32m     83\u001b[0m         \u001b[39mprint\u001b[39m(\u001b[39m\"\u001b[39m\u001b[39mThank You Bye\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m     84\u001b[0m         exit()\n\u001b[0;32m---> 85\u001b[0m main()\n",
      "Cell \u001b[0;32mIn[23], line 69\u001b[0m, in \u001b[0;36mmain\u001b[0;34m()\u001b[0m\n\u001b[1;32m     67\u001b[0m \u001b[39mif\u001b[39;00m user_option \u001b[39m==\u001b[39m \u001b[39m1\u001b[39m:\n\u001b[1;32m     68\u001b[0m     order_number \u001b[39m=\u001b[39m random\u001b[39m.\u001b[39mrandint(\u001b[39m10\u001b[39m, \u001b[39m1000\u001b[39m)\n\u001b[0;32m---> 69\u001b[0m     take_order(order_number)\n\u001b[1;32m     70\u001b[0m \u001b[39melif\u001b[39;00m user_option \u001b[39m==\u001b[39m \u001b[39m2\u001b[39m:\n\u001b[1;32m     71\u001b[0m      edit_order1()\n",
      "Cell \u001b[0;32mIn[23], line 49\u001b[0m, in \u001b[0;36mtake_order\u001b[0;34m(order_number)\u001b[0m\n\u001b[1;32m     45\u001b[0m     get_ipython()\u001b[39m.\u001b[39mrun_line_magic(\u001b[39m'\u001b[39m\u001b[39msql\u001b[39m\u001b[39m'\u001b[39m, \u001b[39m\"\u001b[39m\u001b[39minsert into orders(order_number,dates,hour,food_name,item_no,order_status,payment_status,total_cost)values(\u001b[39m\u001b[39m{order_number}\u001b[39;00m\u001b[39m,\u001b[39m\u001b[39m'\u001b[39m\u001b[39m{date}\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m,\u001b[39m\u001b[39m'\u001b[39m\u001b[39m{time}\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m,\u001b[39m\u001b[39m'\u001b[39m\u001b[39m{food_name}\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m,\u001b[39m\u001b[39m{item_num}\u001b[39;00m\u001b[39m,\u001b[39m\u001b[39m'\u001b[39m\u001b[39m{Status}\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m,\u001b[39m\u001b[39m'\u001b[39m\u001b[39m{Payment}\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m,\u001b[39m\u001b[39m{total_cost}\u001b[39;00m\u001b[39m);\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m     48\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mTotal cost: \u001b[39m\u001b[39m{\u001b[39;00mtotal_cost\u001b[39m:\u001b[39;00m\u001b[39m.2f\u001b[39m\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m)\n\u001b[0;32m---> 49\u001b[0m payment(order_number)\n",
      "Cell \u001b[0;32mIn[19], line 6\u001b[0m, in \u001b[0;36mpayment\u001b[0;34m(order_num)\u001b[0m\n\u001b[1;32m      3\u001b[0m var1 \u001b[39m=\u001b[39m get_ipython()\u001b[39m.\u001b[39mrun_line_magic(\u001b[39m'\u001b[39m\u001b[39msql\u001b[39m\u001b[39m'\u001b[39m, \u001b[39m'\u001b[39m\u001b[39mSELECT total_cost, payment_status FROM orders where orders.order_id = \u001b[39m\u001b[39m{order_num}\u001b[39;00m\u001b[39m;\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[1;32m      4\u001b[0m var2\u001b[39m=\u001b[39m get_ipython()\u001b[39m.\u001b[39mrun_line_magic(\u001b[39m'\u001b[39m\u001b[39msql\u001b[39m\u001b[39m'\u001b[39m, \u001b[39m'\u001b[39m\u001b[39mSelect cash, card FROM store_acc;\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[0;32m----> 6\u001b[0m payment_status \u001b[39m=\u001b[39m var1[\u001b[39m0\u001b[39;49m][\u001b[39m1\u001b[39m]\n\u001b[1;32m      7\u001b[0m cash \u001b[39m=\u001b[39m var2[\u001b[39m0\u001b[39m][\u001b[39m0\u001b[39m]\n\u001b[1;32m      8\u001b[0m card \u001b[39m=\u001b[39m var2[\u001b[39m0\u001b[39m][\u001b[39m1\u001b[39m]\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.10/site-packages/sql/run.py:146\u001b[0m, in \u001b[0;36mResultSet.__getitem__\u001b[0;34m(self, key)\u001b[0m\n\u001b[1;32m    141\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[1;32m    142\u001b[0m \u001b[39mAccess by integer (row position within result set)\u001b[39;00m\n\u001b[1;32m    143\u001b[0m \u001b[39mor by string (value of leftmost column)\u001b[39;00m\n\u001b[1;32m    144\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[1;32m    145\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 146\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mlist\u001b[39;49m\u001b[39m.\u001b[39;49m\u001b[39m__getitem__\u001b[39;49m(\u001b[39mself\u001b[39;49m, key)\n\u001b[1;32m    147\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mTypeError\u001b[39;00m:\n\u001b[1;32m    148\u001b[0m     result \u001b[39m=\u001b[39m [row \u001b[39mfor\u001b[39;00m row \u001b[39min\u001b[39;00m \u001b[39mself\u001b[39m \u001b[39mif\u001b[39;00m row[\u001b[39m0\u001b[39m] \u001b[39m==\u001b[39m key]\n",
      "\u001b[0;31mIndexError\u001b[0m: list index out of range"
     ]
    }
   ],
   "source": [
    "import random\n",
    "import random\n",
    "import datetime\n",
    "now = datetime.datetime.now()\n",
    "\n",
    "%load_ext sql\n",
    "from sqlalchemy import create_engine\n",
    "%sql postgresql://postgres:polpol@localhost:5430/food_ordering_system\n",
    "def take_order(order_number):\n",
    "    menu = {\n",
    "        'burger': 40.00,\n",
    "        'drink': 15.00,\n",
    "        'fries': 20.00,\n",
    "        'wraps': 32.00,\n",
    "        'wings': 43.00,\n",
    "        'lamb chops': 76.00,\n",
    "    }\n",
    "\n",
    "    order = {}\n",
    "    total_cost = 0.0\n",
    "\n",
    "    while True:\n",
    "        food_name = input(\"What would you like to order? (type 'n' to finish) \").lower()\n",
    "        if food_name.lower() == 'n':\n",
    "            Status = 'Preparing'\n",
    "            Payment = 'Not Paid'\n",
    "            break\n",
    "\n",
    "        if food_name not in menu:\n",
    "            print(\"Sorry, we don't have that at the moment.\")\n",
    "            continue\n",
    "\n",
    "        else:\n",
    "            exit\n",
    "\n",
    "        item_num = int(input(f\"How many {food_name}s would you like to order? \"))\n",
    "        total = menu[food_name] * item_num\n",
    "        order[food_name] = item_num\n",
    "        total_cost += total\n",
    "\n",
    "        date = now.strftime(\"%Y-%m-%d\")\n",
    "        time = now.strftime(\"%H:%M:%S\")\n",
    "    print(\"Your order number: \", order_number)\n",
    "    for food_name, item_num,  in order.items():\n",
    "        %sql insert into orders(order_number,dates,hour,food_name,item_no,order_status,payment_status,total_cost)values({order_number},'{date}','{time}','{food_name}',{item_num},'{Status}','{Payment}',{total_cost});\n",
    "\n",
    "    \n",
    "    print(f\"Total cost: {total_cost:.2f}\")\n",
    "    payment(order_number)\n",
    "    \n",
    "    \n",
    "           \n",
    "def main():\n",
    "    main_menu = (\"take_order\", \"edit_order\", \"cancel_order\", \"search_order\")\n",
    "    # while True:\n",
    "    print()\n",
    "    print('choose an option')\n",
    "    print('1-Order_food')\n",
    "    print('2-Edit_order')\n",
    "    print('3-Cancel_order')\n",
    "    print('4-Search_order')\n",
    "    print('5-search_sales_list')\n",
    "\n",
    "    print()\n",
    "    user_option = int(input('option: '))\n",
    "\n",
    "    if user_option == 1:\n",
    "        order_number = random.randint(10, 1000)\n",
    "        take_order(order_number)\n",
    "    elif user_option == 2:\n",
    "         edit_order1()\n",
    "    elif user_option == 3:\n",
    "        cancel_order()\n",
    "    elif user_option == 4:\n",
    "        search()\n",
    "    elif user_option == 5:\n",
    "        search_sales_list()\n",
    "        \n",
    "    Repeat = input(\"Would you like to return to Main_Menu?\").lower()\n",
    "    if Repeat == \"Yes\":\n",
    "        main()\n",
    "    else:\n",
    "        print(\"Thank You Bye\")\n",
    "        exit()\n",
    "main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
